services:
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/db_password
      - POSTGRES_ROOT_PASSWORD_FILE=/run/secrets/db_root_password
    secrets:
      - db_root_password
      - db_password
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"


secrets:
  db_password:
    file: db_password
  db_root_password:
    file: db_root_password

volumes:
  db_data:
